ibgateway:
  # Spécifique à l'environnement
  nodeSelector:
    type: arm64

  image:
    repository: ghcr.io/miletocarmelo/devops_helm_generic_ib_gateway/ib-gateway
    tag: latest-arm64
    pullPolicy: Always

  # Surcharge des variables d'environnement pour l'authentification
  env:
    - name: TWS_USERID
      valueFrom:
        secretKeyRef:
          name: ib-gateway-secrets
          key: TWS_USERID
    - name: TWS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ib-gateway-secrets
          key: TWS_PASSWORD
    - name: IB_ACCOUNT
      valueFrom:
        secretKeyRef:
          name: ib-gateway-secrets
          key: IB_ACCOUNT
    - name: TRADING_MODE
      value: "live"
    - name: BYPASS_WARNING
      value: "yes"
    - name: TIME_ZONE
      value: "Europe/Paris"
    - name: TZ
      value: "Europe/Paris"
    - name: JAVA_HEAP_SIZE
      value: "1024"
    - name: TWS_SETTINGS_PATH
      value: "/config/ibgateway/Jts"   
    - name: VNC_SERVER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ib-gateway-secrets
          key: VNC_SERVER_PASSWORD  


  # Images spécifiques pour les services additionnels
  novnc:
    enabled: true
    image:
      repository: ghcr.io/miletocarmelo/devops_helm_generic_ib_gateway/ib-gateway-novnc
      tag: latest-arm64
      pullPolicy: Always
    service:
      type: NodePort
      port: 6080
      containerPort: 6080

  vnc:
    enabled: true
    password: "1234" 

  pythonService:
    image:
      repository: ghcr.io/miletocarmelo/devops_helm_generic_ib_gateway/ib-gateway-python-service
      tag: latest-arm64
      pullPolicy: Always