ibgateway:

  secret:
    name: "ib-gateway-secrets"

  ibgateway:
    mode: "live"
    port: "4001"
    apiPort: "4002"
    timezone: "Europe/Paris"

  # fait reférence à limage ibgateway
  image:
    repository: ghcr.io/miletocarmelo/devops_helm_generic_ib_gateway/ib-gateway
    tag: latest-arm64  # Spécifiez le tag pour ARM64
    pullPolicy: Always


  novnc:
    enabled: true
    image:
      repository: ghcr.io/miletocarmelo/devops_helm_generic_ib_gateway/ib-gateway-novnc
      tag: latest-arm64  # Spécifiez le tag pour ARM64
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 6080
    display:
      width: "1280"
      height: "720"

  vnc:
    enabled: true
    port: "5900"
    password: "myVNCpass"