ibgateway:
  # Spécifique à l'environnement
  nodeSelector:
    type: arm64

  image:
    repository: ghcr.io/miletocarmelo/devops_helm_generic_ib_gateway/ib-gateway
    tag: latest-arm64
    pullPolicy: Always

  # Surcharge des variables d'environnement pour l'authentification
  env:
    - name: TWS_USERID
      valueFrom:
        secretKeyRef:
          name: ib-gateway-secrets
          key: TWS_USERID
    - name: TWS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ib-gateway-secrets
          key: TWS_PASSWORD
    - name: IB_ACCOUNT
      valueFrom:
        secretKeyRef:
          name: ib-gateway-secrets
          key: IB_ACCOUNT

  # Images spécifiques pour les services additionnels
  novnc:
    image:
      repository: ghcr.io/miletocarmelo/devops_helm_generic_ib_gateway/ib-gateway-novnc
      tag: latest-arm64
      pullPolicy: Always

  pythonService:
    image:
      repository: ghcr.io/miletocarmelo/devops_helm_generic_ib_gateway/ib-gateway-python-service
      tag: latest-arm64
      pullPolicy: Always